#ifndef NXP_MBEDTLS_CONFIG_H
#define NXP_MBEDTLS_CONFIG_H

#undef MBEDTLS_ERROR_C
#ifdef USE_HW_CRYPTO
#define MBEDTLS_SHA256_PROCESS_ALT
#define MBEDTLS_ARMV8CE_AES_C
#define MBEDTLS_ARMV8CE_DEBUG
#endif

#endif /* !NXP_MBEDTLS_CONFIG_H */
