/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __ARM_SYSREGS_H__
#define __ARM_SYSREGS_H__

/* MPIDR_EL1 */
#define MPIDR_AFF_MASK		0xFF

#define MPIDR_AFF0_SHIFT	0
#define MPIDR_AFF1_SHIFT	8
#define MPIDR_AFF2_SHIFT	16
#define MPIDR_AFF3_SHIFT	32

#define MPIDR_AFF0_MASK		(MPIDR_AFF_MASK << MPIDR_AFF0_SHIFT)
#define MPIDR_AFF1_MASK		(MPIDR_AFF_MASK << MPIDR_AFF1_SHIFT)
#define MPIDR_AFF2_MASK		(MPIDR_AFF_MASK << MPIDR_AFF2_SHIFT)
#define MPIDR_AFF3_MASK		(MPIDR_AFF_MASK << MPIDR_AFF3_SHIFT)

#define MPIDR_MT		(1 << 24)
#define MPIDR_U			(1 << 30)

/* VTCR_EL2 */
#define VTCR_TG0_SHIFT		14
#define VTCR_TG0_MASK		(3 << VTCR_TG0_SHIFT)
#define VTCR_TG0(x)		((x & VTCR_TG0_MASK) >> VTCR_TG0_SHIFT)
#define VTCR_GET_GRANULE_SIZE	VTCR_TG0
#define GRANULE_SIZE_4KB	0
#define GRANULE_SIZE_16KB	2
#define GRANULE_SIZE_64KB	1

#define VTCR_SL0_SHIFT		6
#define VTCR_SL0_MASK		(3 << VTCR_SL0_SHIFT)
#define VTCR_SL0(x)		((x & VTCR_SL0_MASK) >> VTCR_SL0_SHIFT)

#endif // __ARM_SYSREGS_H__
