override CC := gcc
override LD := ld
override CXX :=
override CPP :=
override CFLAGS := -Wall -O2 -g
override LDFLAGS :=
override MAKEFLAGS :=
override LDLAGS :=
override LDLIBS :=
override SANITIZER_OPTS:=
