/* Sysconfig */
#define MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE
#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_FS_IO
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_PLATFORM_SNPRINTF_ALT
#define MBEDTLS_DEPRECATED_WARNING

/* Entropy config */
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_NO_PLATFORM_ENTROPY

/* Crypto options */
#define MBEDTLS_AES_C
#define MBEDTLS_CIPHER_MODE_CTR
#undef MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH
