/* Sysconfig */
#define MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE
#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_FS_IO
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_PLATFORM_SNPRINTF_ALT
#define MBEDTLS_DEPRECATED_WARNING
#ifndef TESTS
#undef MBEDTLS_ERROR_C
#define MBEDTLS_ERROR_STRERROR_DUMMY
#endif

/* Entropy config */
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_MAX_SOURCES 2

/* Crypto options */
#define MBEDTLS_AES_C
#define MBEDTLS_CIPHER_MODE_CTR
#define MBEDTLS_SHA256_NO_SHA224
#define MBEDTLS_AES_FEWER_TABLES
#define MBEDTLS_CIPHER_MODE_WITH_PADDING
#define MBEDTLS_CIPHER_PADDING_ZEROS
#undef MBEDTLS_ARC4_C
#undef MBEDTLS_CIPHER_MODE_CBC
#undef MBEDTLS_CIPHER_MODE_CCM
#undef MBEDTLS_CIPHER_MODE_ECB
#undef MBEDTLS_CIPHER_MODE_GCM
#undef MBEDTLS_BLOWFISH_C
#undef MBEDTLS_CHACHA20_C
#undef MBEDTLS_CHACHAPOLY_C
#undef MBEDTLS_CAMELLIA_C
#undef MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH
#undef MBEDTLS_SHA512_C
#undef MBEDTLS_CIPHER_MODE_CFB
#undef MBEDTLS_CIPHER_MODE_OFB
#undef MBEDTLS_CIPHER_MODE_XTS


/* Platform specific */
#ifdef PLATFORM_MBEDTLS_CONFIG
#include PLATFORM_MBEDTLS_CONFIG
#endif /* PLATFORM_MBEDTLS_CONFIG */
