#define GUEST_MEM_MAX 0x200000000
#define STATIC_TTBL_NUM	256
#define HOSTBLINDING 1
#define KVM_GUEST_SUPPORT 1
#define PLATFORM_MBEDTLS_CONFIG "virt_mbedtls_config.h"
#define HOST_SWAP_ENCRYPTION 1
