#!/system/bin/sh
#
# Script to bring a network (tap) device for qemu up.

PATH=$PATH:/sbin:/usr/sbin
#WAYOUT=$(ip route show |grep default |cut -d " " -f 5)
WAYOUT=wlan0

ifconfig $1 up 192.168.7.1
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
